### ISSUE TITLE
[Bug Report] - Mini Pet Creeper/Baby Zombie attack and kill

### ISSUE THREAD

**Issue by laxlacks888** [MiniaturePets/Issues#317] opened 2022-06-25 00:20 UTC
# Bug Report

### Technical Information
* Server Software:  1.18.2 paper
* Plugin Version:  2.7.4-stable
* Dump File: 
> Use `/mpet dump` to get the dump file.
[Miniature Pets Dump 2022-06-25 00 19 06.txt](https://github.com/MiniaturePets/Issues/files/8983566/Miniature.Pets.Dump.2022-06-25.00.19.06.txt)

### General Information

We are still in the process of setting up our server, when we first installed the plugin a few weeks ago everything worked great.  Today we updated and decided to do some more testing, and when we spawned a creeper pet it blew up like a normal in game creeper.  Tried again with a baby zombie and it killed me.  Tried again with both the creeper and baby zombie and I could not attack them but they both could kill me.  The only way I could get rid of them was to dismiss them in the pet gui.  I looked through the config file and couldn't find anything related to this issue.

**Comment by Aurillium** [comment] 2022-07-02 04:28
Hi! Does your server console provide any information about this? Often if something doesn't work as intended there will be an error message which will help us find the issue faster.
Also what did you change between first installing the plugin and it not working?
If you know any extra details please let us know because it will help us find the issue faster

**Comment by laxlacks888** [comment] 2022-07-02 23:03
No errors or warnings in the console.  I did update to the newest version (today) and retested, and the creeper still blows up.

The only thing that changed was I updated the plugin to 2.7.4, and now to 2.7.5.  

Our plugins are;
AlonsoTags
AsyncWorldEdit
Boosters
BungeeGuard
Chatcolors2
ChatFeelings
ChatItem
Citizens
CoreProtect
DeluxeHub
Drugs
Eco
eGlow
EliteAPI
AliteArmor
EssentialsChat
EssentialsDiscord
EssentialsSpawn
IllegalStack
LagAssist
LibsDisguises
LuckPerms
MiniaturePets
Multiverse-Core
Multiverse-Portals
NametageEdit
NBTAPI
Panilla
Pl-Hide-Pro
PlaceholderAPI
PlayerParticles
PlayerVaults
PremiumVanish
ProtocolLib
Spartan
TicketGUI
Vault
ViaVersion
WorldEdit
WorldGuard

Hopefully this helps.

**Comment by laxlacks888** [comment] 2022-07-02 23:06
Also maybe if this will help, this is our config.yml

checkForUpdates: true
disablePlugin: false
useWorldGuard: true
usePackets: true
useHats: true
useDisguises: true
useRide: true
useInteractGUI: true
debug: false
combatTag: false
petPunch: true
useHopperGUI: true
handlePlayerData: true
PetExtraRemoval: false
runGUIAsync: true
perPetName: true
hideDisguisedPlayers: true
respawnOnFallingToVoid: true
animationRefreshRate: 2
standardizedPermissions: false
dismountOnWater: false
bypassSpawnProtections: false
minimumPetTeleportRange: 40.0
petTeleportCheckSeconds: 6.0
disallowDisguiseTeleport: true
respawnPetOnWorldMove: false
downloadDefaultPetsIfNone: true
disallowedPetNameWords:
- GAMERS
- RISE
- UP
respawnPetOnJoin: false
petLoadingMessage: false
despawnOnGamemodeChangeTo:
- LIST
- OF
- GAMEMODES
petDistance: 4
SaveWithUUID: true
PetSpawnDistance: -3
PetNameLimit: 20

**Comment by Aurillium** [comment] 2022-07-10 08:07
Thank you! We're still looking into this

**Comment by laxlacks888** [comment] 2022-07-13 00:38
Ok so I thought I'd offer an update.  I thought, what if one of our other plugins is causing an issue.  So I installed a completely new paper (version paper-1.18.2-387) server with no mods or plugins other than the newest minipets (version MiniaturePets_v2.7.6-stable).  New install of client, 1,18,2, zero mods, not even shaders, new world generated.  No configs changed, only added in the pet files.  Fresh start of the world, Minipets tells me the plugin is outdated, but it is the newest, downloaded today.  Summoned a creeper, a skeleton, and a zombie.  All three attacked and killed me.

I decided to go back several versions and start working my way forward.

Version 2.6.9 the creeper does NOT blow up or attack.
Version 2.7.0 the creeper does NOT blow up or attack.
Version 2.7.1 the creeper does NOT blow up or attack.
Version 2.7.2 the creeper does NOT blow up or attack.
Version 2.7.3 the creeper does blow up and attack.
Going forward they all attack and blow up.

I hope this info helps.

**Comment by laxlacks888** [comment] 2022-07-21 01:10
I just tried the newest, 2.7.7 on the same new 1.18.2 vanilla install as stated in my last comment.  Same issue, the creeper blows up and hurts/kills me.

**Comment by Awpmeister2170** [comment] 2022-07-23 01:32
Should be fixed with the latest update :) please update your versions

**Closed as completed by Awpmeister2170** 2022-07-23 01:32 UTC
Labels: Bug

**Comment by laxlacks888** [comment] 2022-07-23 03:11
Tested and it works great!  Thank you!
