### ISSUE TITLE
Failure To Use Custom Model Data

### ISSUE THREAD

**Issue by CookiesNom** [miniaturepets/issues#193] opened 2020-07-03 20:54 UTC
# Bug Report

### Technical Information
* Old Miniature Pets Version: 2.3.8
* New Miniature Pets Version: 2.4.3
* Dump File: Had to shut down and swap back immediately
* Server Version : Paper version git-Paper-655 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### General Information
We also use Via Version, not sure if that would affect it but is worth mentioning.

**Bug Description**
Constant error in console, I use damage value items for my limbs, not sure why it would need to use "CustomModelData" since thats a whole other NBT tag and not related at all. Since we are running 1.13 we cant use "CustomModelData"
```
[03:10:15] [Server thread/WARN]: java.lang.NoSuchMethodException: No such accessible method: setCustomModelData() on object: org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem
```

**Logs**
```
[03:10:14] [Server thread/INFO]: [MiniaturePets] Enabling MiniaturePets v2.4.3*
[03:10:14] [Server thread/INFO]: [MiniaturePets] Loading reflections.
[03:10:14] [Server thread/INFO]: [MiniaturePets] The packet 'PacketPlayInSteerVehicle' has been added to the packet handler.
[03:10:15] [Server thread/INFO]: [MiniaturePets] Starting to calculate Radians!
[03:10:15] [Server thread/WARN]: java.lang.NoSuchMethodException: No such accessible method: setCustomModelData() on object: org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem
[03:10:15] [Server thread/WARN]: 	at org.apache.commons.lang.reflect.MethodUtils.invokeExactMethod(MethodUtils.java:262)
[03:10:15] [Server thread/WARN]: 	at org.apache.commons.lang.reflect.MethodUtils.invokeExactMethod(MethodUtils.java:227)
[03:10:15] [Server thread/WARN]: 	at org.apache.commons.lang.reflect.MethodUtils.invokeExactMethod(MethodUtils.java:195)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.loader.ItemLoader.loadItem(ItemLoader.java:114)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.loader.ItemLoader.<init>(ItemLoader.java:37)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.loader.files.PetFile.<init>(PetFile.java:29)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.loader.PetLoader.registerFromFile(PetLoader.java:84)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.loader.PetLoader.<init>(PetLoader.java:47)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.MiniaturePets.load(MiniaturePets.java:398)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.MiniaturePets.onEnable(MiniaturePets.java:186)
[03:10:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[03:10:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
[03:10:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[03:10:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[03:10:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[03:10:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[03:10:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[03:10:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[03:10:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[03:10:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[03:10:15] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[03:10:15] [Server thread/WARN]: java.lang.NoSuchMethodException: No such accessible method: setCustomModelData() on object: org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem
[03:10:15] [Server thread/WARN]: 	at org.apache.commons.lang.reflect.MethodUtils.invokeExactMethod(MethodUtils.java:262)
[03:10:15] [Server thread/WARN]: 	at org.apache.commons.lang.reflect.MethodUtils.invokeExactMethod(MethodUtils.java:227)
[03:10:15] [Server thread/WARN]: 	at org.apache.commons.lang.reflect.MethodUtils.invokeExactMethod(MethodUtils.java:195)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.loader.ItemLoader.loadItem(ItemLoader.java:114)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.loader.ItemLoader.<init>(ItemLoader.java:37)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.loader.files.PetFile.<init>(PetFile.java:29)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.loader.PetLoader.registerFromFile(PetLoader.java:84)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.loader.PetLoader.<init>(PetLoader.java:47)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.MiniaturePets.load(MiniaturePets.java:398)
[03:10:15] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.MiniaturePets.onEnable(MiniaturePets.java:186)
[03:10:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[03:10:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
[03:10:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[03:10:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[03:10:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[03:10:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[03:10:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[03:10:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[03:10:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[03:10:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[03:10:15] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by danielnaaman** [comment] 2020-07-04 13:32
Possible duplicate of #171 - please wait patiently until we further examine this issue.

**Comment by danielnaaman** [comment] 2020-07-31 15:27
Closed, duplicate.

**Closed** 2020-07-31 15:28 UTC
Labels: Bug Report, Duplicate, Pending Review

**Comment by danielnaaman** [comment] 2020-09-15 16:57
@CookiesNom This is an update to let you know that this has been fixed and will be seen in the next release of Miniature Pets :)
