### ISSUE TITLE
Custom Pets Break On Recent Spigot Versions

### ISSUE THREAD

**Issue by pacificminer** [miniaturepets/issues#171] opened 2020-04-08 11:27 UTC
Custom pets despawn. It seems that ever since this change that my custom pets no longer will spawn: https://github.com/PaperMC/Paper/commit/859f1296fe05f28df5379fba59c9f1d93551474b

This is how it looks when trying to summon my pet with every paper version above the commit change above: https://gyazo.com/4c97f346957299b356797899f51f2ecf

When trying b87 - one of the first 1.15.2 builds, it works, but each paper version from that point it does not work. https://i.gyazo.com/893f2e566e8da4f2c2eda49355eac511.png

Tried with MiniaturePets version 2.3.7, 2.3.8 and 2.3.9. Issues persist across all versions, so it appears it broke after the paper change. Hopefully, this can be solved.

**Comment by liorsl** [comment] 2020-04-15 18:44
Hello,
Is the custom pet based on a hostile mob?

**Comment by danielnaaman** [comment] 2020-04-21 15:06
@pacificminer This issue is waiting for your answer, please respond within 24 hours or it will be closed.

**Comment by pacificminer** [comment] 2020-04-22 09:58
No, it's not, as we've already discussed on Discord.

**Comment by liorsl** [comment] 2020-04-25 11:06
Are you using WorldGuard?

**Comment by pacificminer** [comment] 2020-04-25 12:55
> Are you using WorldGuard?

Yes, worldguard is installed on the server, though I've tried spawning the pets both in a Worldguard region and outside of one. Issue persists.

**Comment by liorsl** [comment] 2020-04-25 13:07
Did you disable 'block-plugin-spawning' in worldguard's config?

**Comment by pacificminer** [comment] 2020-04-25 13:14
No, I've never used that.

**Comment by pacificminer** [comment] 2020-04-25 13:15
It's set to false in the Worldguard config.yml

>     block-plugin-spawning: false

**Comment by pacificminer** [comment] 2020-04-25 13:25
Just tried it on a server without any plugins installed except MiniaturePets. Using the very first paper 1.15 jar it works properly. Using any more recent jar and it doesn't.

**Comment by NacOJerk** [comment] 2020-04-25 13:41
Hey pacificminer, we tried using paperspigot (the latest one we found online) and we couldn't reproduce the bug

Could you please send us the server jar you are using?

**Comment by pacificminer** [comment] 2020-05-31 22:32
Ridiculous this hasn't been fixed yet. It's been almost 2 months. Daniel told me on Discord when initially reported that it'd be fixed within a few days.

**Comment by danielnaaman** [comment] 2020-06-01 15:18
> Ridiculous this hasn't been fixed yet. It's been almost 2 months. Daniel told me on Discord when initially reported that it'd be fixed within a few days.

This is what I initially hoped for, sorry for those extreme delays. I really hope to see this released soon, I can't promise anything further.

Know that, it will be fixed eventually.

Daniel.

**Comment by danielnaaman** [comment] 2020-07-03 13:28
This has been confirmed to happen on regular Spigot as well, progress is being made though I wouldn't expect to see it live on the next version, this requires some changes to how the plugin handles custom model data. For the meantime, this conversation has been locked.

**Comment by danielnaaman** [comment] 2020-09-12 20:12
Fixed, praise @UltraFaceguy <3

**Closed by danielnaaman** 2020-09-12 20:12 UTC
Labels: Bug Report, Low Priority
